### ISSUE TITLE
Update PyReconer to use eyewitness

### ISSUE THREAD

**Issue by sneakerhax** [sneakerhax/Arsenal#19]
**Details:**

[PyReconer](https://github.com/sneakerhax/Arsenal/tree/main/Containers/PyReconer) currently uses [Aquatone](https://github.com/michenriksen/aquatone) for screen shots of targets. This tool has not been updated since 2019. [Eyewitness](https://github.com/FortyNorthSecurity/EyeWitness) has continued updates and features.

**Request:**

Replace the functionality of Aquatone to perform screenshots with Eyewitness

**Required** 

- [x] Updated the Dockerfile to use the image python:3-slim (supported by Eyewitness)
- [x] Update the Dockerfile to remove aquatone functionality
- [x] Update the Dockerfile to install Eyewitness
- [x] Remove the [binary location variables](https://github.com/sneakerhax/Arsenal/blob/bfef9ce9743de185c67cc0c7fc63a7c701bbaf91/Containers/PyReconer/PyReconer.py#L6) from PyReconer.py for aquatone
- [x] Add the binary location variable for Eyewitness to PyReconer.py
- [x] Remove the [output location](https://github.com/sneakerhax/Arsenal/blob/bfef9ce9743de185c67cc0c7fc63a7c701bbaf91/Containers/PyReconer/PyReconer.py#L17) for aquatone
- [x] Add the output location for Eyewitness
- [x] Remove the function [aquatone_screen_grab](https://github.com/sneakerhax/Arsenal/blob/bfef9ce9743de185c67cc0c7fc63a7c701bbaf91/Containers/PyReconer/PyReconer.py#L57) and [calls](https://github.com/sneakerhax/Arsenal/blob/bfef9ce9743de185c67cc0c7fc63a7c701bbaf91/Containers/PyReconer/PyReconer.py#L72) to the function
- [x] Add the function eyewitness_screen_grab to PyReconer.py
- [x] Call the function eyewitness_screen_grab as part of the automation flow
- [x] Ensure you can download the eyewitness results by updating [run_reconer.sh](https://github.com/sneakerhax/Arsenal/blob/main/Containers/PyReconer/run_reconer.sh) if necessary
- [x] Post proof of these changes working in the pull request
- [x] Get your pull request approved
- [x] Request closure of this issue

**Comment by sudo-phantom** [comment]
pull requst 
https://github.com/sneakerhax/Arsenal/pull/23

**Comment by sneakerhax** [comment]
@sudo-phantom I updated the checklist

Additional items to update:

- [ ] Remove [Chromium](https://github.com/sneakerhax/Arsenal/blob/e53867ccc64e4c0616c3406b5f3b7c13c989819f/Containers/PyReconer/Dockerfile#L10) install in the Dockerfile (only required for aquatone)
- [ ] Remove Chromium [binary location variable](https://github.com/sneakerhax/Arsenal/blob/e53867ccc64e4c0616c3406b5f3b7c13c989819f/Containers/PyReconer/PyReconer.py#L7)
- [ ] Remove the install of [Nmap-Scan-to-CSV](https://github.com/sneakerhax/Arsenal/blob/e53867ccc64e4c0616c3406b5f3b7c13c989819f/Containers/PyReconer/Dockerfile#L11) in the Dockerfile (only required by aquatone)
- [ ] Update Eyewitness to install by git clone (Eyewitness package does not have latest tag)
- [ ] Cleanup Python install (python:3-slim image already has Python)

**Comment by sneakerhax** [comment]
Added commit 5cccb336e6a4801b3f6fd8c7492f6d5687750af9 to fix remaining issues.
